//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consist.RapidEntity.DslPackage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "rapd";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"RapidEntity";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"consist";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID RapidEntityDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RapidEntityCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID RapidEntityExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RapidEntityCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewRapidEntityExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RapidEntityCommandSetId), 0x0001);
	
		// Package identifier
		public const string RapidEntityPackageId = "ae24ea31-9883-4087-9e20-23e7b5a79ba3";
		
		// Editor factory identifier
		public const string RapidEntityEditorFactoryId = "fef902f3-b77f-40d9-9229-02580c178cb8";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string RapidEntityModelExplorerToolWindowId = "20fc2e25-12d7-41b9-b100-594e01ed6fc7";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace consist.RapidEntity.DslPackage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string RapidEntityCommandSetId = "a8652aee-b64b-4a21-8bce-cb55b0ba4ff6";
	}
}