//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistentManager.Query.XmlQueryAPI
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( AnonymousType = true , Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    [System.Xml.Serialization.XmlRootAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" , IsNullable = false )]
    public partial class Query
    {

        private FromType fromField;

        private WhereType whereField;

        private GroupByType groupByField;

        private OrderbyAscendingType orderByAscendingField;

        private OrderbyDescendingType orderbyDescendingField;

        private SelectType selectField;

        private RowSetType[] rowField;

        private string versionField;

        public Query( )
        {
            this.versionField = "1.0";
        }

        /// <remarks/>
        public FromType From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        public WhereType Where
        {
            get
            {
                return this.whereField;
            }
            set
            {
                this.whereField = value;
            }
        }

        /// <remarks/>
        public GroupByType GroupBy
        {
            get
            {
                return this.groupByField;
            }
            set
            {
                this.groupByField = value;
            }
        }

        /// <remarks/>
        public OrderbyAscendingType OrderByAscending
        {
            get
            {
                return this.orderByAscendingField;
            }
            set
            {
                this.orderByAscendingField = value;
            }
        }

        /// <remarks/>
        public OrderbyDescendingType OrderbyDescending
        {
            get
            {
                return this.orderbyDescendingField;
            }
            set
            {
                this.orderbyDescendingField = value;
            }
        }

        /// <remarks/>
        public SelectType Select
        {
            get
            {
                return this.selectField;
            }
            set
            {
                this.selectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "row" )]
        public RowSetType[] row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        [System.ComponentModel.DefaultValueAttribute( "1.0" )]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class FromType
    {

        private JoinType joinField;

        private InType inField;

        private string typeofField;

        private string asField;

        /// <remarks/>
        public JoinType Join
        {
            get
            {
                return this.joinField;
            }
            set
            {
                this.joinField = value;
            }
        }

        /// <remarks/>
        public InType In
        {
            get
            {
                return this.inField;
            }
            set
            {
                this.inField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string Typeof
        {
            get
            {
                return this.typeofField;
            }
            set
            {
                this.typeofField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string As
        {
            get
            {
                return this.asField;
            }
            set
            {
                this.asField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class JoinType
    {

        private string propertyField;

        private string asField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string As
        {
            get
            {
                return this.asField;
            }
            set
            {
                this.asField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class ColumnSetType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class RowSetType
    {

        private ColumnSetType[] columnField;

        private string rowidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "column" )]
        public ColumnSetType[] column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( DataType = "integer" )]
        public string rowid
        {
            get
            {
                return this.rowidField;
            }
            set
            {
                this.rowidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class SelectType
    {

        private ExpressionType[] expressionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Expression" )]
        public ExpressionType[] Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class ExpressionType
    {

        private string nameField;

        private ConditionalType conditionField;

        private string valueField;

        public ExpressionType( )
        {
            this.conditionField = ConditionalType.NOTSET;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        [System.ComponentModel.DefaultValueAttribute( ConditionalType.NOTSET )]
        public ConditionalType Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public enum ConditionalType
    {

        /// <remarks/>
        Equals ,

        /// <remarks/>
        GreaterThan ,

        /// <remarks/>
        LessThan ,

        /// <remarks/>
        GreaterThanEqualsTo ,

        /// <remarks/>
        LessThanEqualsTo ,

        /// <remarks/>
        NotEquals ,

        /// <remarks/>
        Is ,

        /// <remarks/>
        IsNull ,

        /// <remarks/>
        IsNotNull ,

        /// <remarks/>
        StartsWith ,

        /// <remarks/>
        EndsWith ,

        /// <remarks/>
        Contains ,

        /// <remarks/>
        NotContains ,

        /// <remarks/>
        IN ,

        /// <remarks/>
        NOT_IN ,

        /// <remarks/>
        Between ,

        /// <remarks/>
        NOTSET ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class OrderbyDescendingType
    {

        private ExpressionType[] expressionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Expression" )]
        public ExpressionType[] Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class OrderbyAscendingType
    {

        private ExpressionType[] expressionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Expression" )]
        public ExpressionType[] Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class GroupByType
    {

        private ExpressionType[] expressionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Expression" )]
        public ExpressionType[] Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class WhereType
    {

        private ExpressionType[] expressionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute( "Expression" )]
        public ExpressionType[] Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "xsd" , "2.0.50727.3038" )]
    [System.SerializableAttribute( )]
    [System.Diagnostics.DebuggerStepThroughAttribute( )]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.XmlTypeAttribute( Namespace = "http://rql-rapid.org/RapidXmlSchema.xsd" )]
    public partial class InType
    {

        private string propertyField;

        private string asField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string Property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute( )]
        public string As
        {
            get
            {
                return this.asField;
            }
            set
            {
                this.asField = value;
            }
        }
    }
}
